elec <- read.table("household_power_consumption.txt", sep=";", na.strings = "?", header = TRUE)
elec$Date <- as.Date(elec$Date, "%d/%m/%Y")
elec <- subset(elec , Date == "2007-02-01" | Date ==  "2007-02-02")
png(filename = "plot1.png", width = 480, height = 480)
hist(elec$Global_active_power, col = "red",xlab="Global Active Power (kilowatts)", main= "Global Active Power")
dev.off()