elec <- read.table("household_power_consumption.txt", sep=";", na.strings = "?", header = TRUE)
elec <- subset(elec , Date == "1/2/2007" | Date ==  "2/2/2007")
elec$datetime <- strptime(paste(elec$Date, elec$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 

png(filename = "plot3.png", width = 480, height = 480)
plot(elec$datetime, elec$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(elec$datetime, elec$Sub_metering_2, type="l", col="red")
lines(elec$datetime, elec$Sub_metering_3, type="l", col="blue")
legend("topright", lty=1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),col=c("black", "red", "blue"))
dev.off()
